weather/cities/urls.py
from django.urls import path
from .views import CityMapView

app_name = "cities"

urlpatterns = [
    path("map/", CityMapView.as_view())
]

weather/weather/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import WeatherView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', WeatherView.as_view(), name='home'),
    
    path('city/', include('cities.urls'))
]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/weather/forms.py
from django.contrib.gis import forms


# class OSMWidget(forms.OSMWidget):
#     class Media:
#         js = ('openlayers.js')
        
class GeoForm(forms.Form):
    point = forms.PointField(widget=
        forms.OSMWidget(attrs={'map_width': '100%', 'map_height': '100%', 'supports_3d':True, 'default_lat':"14.599512", 'default_long':'120.984222'}))
    
    
    def __init__(self,*args,**kwargs):
        super (GeoForm,self ).__init__(*args,**kwargs)
        self.fields['point'].label = ''

weather/templates/index.html
{% load static %}

<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
<meta name="generator" content="Hugo 0.88.1">
<title>Weather weather lang!</title>

<link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/pricing/">

<link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<link href="{% static 'map.css' %}" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="{% static '/assets/img/favicons/apple-touch-icon.png' %}" sizes="180x180">
<link rel="icon" href="{% static '/assets/img/favicons/favicon-32x32.png' %}" sizes="32x32" type="image/png">
<link rel="icon" href="{% static '/assets/img/favicons/favicon-16x16.png' %}" sizes="16x16" type="image/png">
<link rel="manifest" href="{% static '/assets/img/favicons/manifest.json' %}">
<link rel="mask-icon" href="{% static '/assets/img/favicons/safari-pinned-tab.svg' %}" color="#563d7c">
<link rel="icon" href="{% static '/assets/img/favicons/favicon.ico' %}">
<meta name="msapplication-config" content="{% static '/assets/img/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#563d7c">


<script src="{% static 'bootstrap/dist/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

{{ form.media }}
<link href="{% static 'leaflet/leaflet.css' %}" rel="stylesheet">
<script src="{% static 'leaflet/leaflet.js' %}"></script>

</head>
<body>
    
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Weather-Weather Lang!</h5>
    </div>


    <section class="wrapper">
        <div class="row w-100 h-100">
            <div class="col-12 col-lg-7 left-col p-0">
                <div class="container h-100">
                    <div id='rowWrap' class="row">
                        {% include 'fragments/forecast.html' %}
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <form id="form" method='POST' action="javascript:void(0);" class="form" role="form">
                    {% csrf_token %}
                    {% comment %} {{ form }} {% endcomment %}
                    {{ city|json_script:"city-data"}}
                    <div id="map" class="w-100 h-100"></div>
                    <input id="lat" type="hidden" name="lat">
                    <input id="lon" type="hidden" name="lon">

                </form>
            </div>
        </div>
        
    </section>


<script src="{% static 'blockui/jquery.blockUI.min.js' %}"></script> 
<script src="{% static 'blockui/custom-blockui.js' %}"></script> 
<script>
navigator.geolocation.getCurrentPosition(onSuccess);

function onSuccess(position) {
    const {
        latitude,
        longitude
    } = position.coords;
    console.log(position.coords)
}

$(document).ready(function(){
    let point = $("#id_point");

    point.on('change', function(){
        console.log($(this).val())
    })
})

const copy = '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors.';
const url = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
const osm = L.tileLayer(url, {attribution:copy});
const map = L.map("map", {layers:[osm], minZoom:5});
const cities = JSON.parse(document.getElementById("city-data").textContent);
let features = L.geoJSON(cities).bindPopup(layer => layer.feature.properties.name);
console.log(features)

map.addLayer(features).fitBounds(features.getBounds());
map.setZoom(12);
map.on('click', addMarker);

let removeFeature = false;
{% comment %} function to use to put a marker on the map {% endcomment %}
function addMarker(e){
    if(!removeFeature){
        features.clearLayers();
        removeFeature = true;
    }else{
        features.remove()
    }
    console.log(e.latlng)
    
// Add marker to map at click location; add popup window
    features = new L.marker(e.latlng).addTo(map);
    getWeatherForecast(e.latlng);
}

function getWeatherForecast(v){
    $('#lat').val(v.lat);
    $('#lon').val(v.lng);
    $('#map').block({
        overlayCSS: {
            backgroundColor: '#fff',
            opacity: 0.8,
            cursor: 'wait'
        },
        css: {
            border: 0,
            padding: 0,
            color: '#e7515a',
            backgroundColor: 'transparent'
        }
    });
    $.ajax({
        type: 'POST',
        dataType: "json",
        url: window.location.href,
        data: $("#form").serialize(),
        cache:false,
        success:function(res) {
            console.log(res)
            if(res.status===200 && res.data){
                $("#rowWrap").html(res.data);
            }

            $('#map').unblock();
        }
    })
}

</script>
</body>